#!/usr/bin/env ruby
require 'pathname'

# path to application root
APP_ROOT = Pathname.new File.expand_path('../../',  __FILE__)

puts "Application located in #{APP_ROOT}."

Dir.chdir APP_ROOT do
  puts '== Installing dependencies =='
  # this special incantation is required for installing debugger gems
  system 'gem install bundler'
  system 'gem install rake'
  system 'gem install debugger-ruby_core_source --pre'
  system 'gem install ruby-debug-ide --pre'
  system 'bundle install'

  system 'bundle check || bundle install'

  puts "\n== Removing logs, tempfiles, docs, and test results =="
  system 'rm -f log/*'
  system 'rm -rf tmp/*'
  system 'rm -rf coverage'
  system 'rm -rf doc'

  puts "\n== Further Setup =="
  puts "Note: Remember to check config/settings/development.yml and config/settings/test.yml.\n\tThey are based on config/settings/default.yml"

  puts 'Prepare the local development database:`bin/rake db:setup RAILS_ENV=development`'
  system 'bin/rake db:setup RAILS_ENV=development'

  puts 'Prepare the local test database:`bin/rake db:setup RAILS_ENV=test`'
  system 'bin/rake db:setup RAILS_ENV=test'
end
