source 'https://rubygems.org'

# Specify your gem's dependencies in baw-workers.gemspec
gemspec

# added here because gemspec doesn't support getting gems from urls
gem 'baw-audio-tools', path: '../baw-audio-tools'

gem 'resque-job-stats', git: 'https://github.com/echannel/resque-job-stats.git', branch: :master, ref: '8932c036'