
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
  TargetRubyVersion: 2.5
# Rails:
#   Enabled: true

# Customized options
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Layout/LineLength:
  Max: 120
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EndOfLine:
  EnforcedStyle: lf
# We sometimes leave commented out code in the code base
Layout/LeadingCommentSpace:
  Enabled: false
Metrics/ClassLength:
  Max: 300
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Metrics/BlockLength:
  ExcludedMethods:
    - resource
    - describe
    - shared_examples_for
    - shared_context
    - context
    - it
    - group
    - namespace
Metrics/MethodLength:
  Max: 30
  ExcludedMethods:
    - filter_settings
Metrics/AbcSize:
  Max: 60
Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowBracesOnProceduralOneLiners: true
Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: scientific
Style/HashEachMethods:
  Enabled: true
  AutoCorrect: false
Style/HashTransformKeys:
  Enabled: true
  AutoCorrect: false
Style/HashTransformValues:
  Enabled: true
  AutoCorrect: false
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
