---
include:
- "**/*.rb"
exclude:
# - spec/**/*
# - test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  - typecheck:strict
  - update_errors
require_paths:
  - spec/lib
  - spec/helpers
  - spec
  - lib
formatter:
  rubocop:
    cops: all
max_files: 5000
