---
include:
- "**/*.rb"
exclude:
# - spec/**/*
# - test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
  - semantic_logger
domains: []
reporters:
  - rubocop
  - require_not_found
  - typecheck:typed
  - update_errors
require_paths:
  - spec/lib
  - spec/support
  - spec
  - lib
formatter:
  rubocop:
    cops: all
max_files: 5000
plugins:
  - solargraph-rails
