=begin
#SFTPGo

#SFTPGo REST API

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module SftpgoGeneratedClient
  class LoginMethods
    PUBLICKEY = "publickey".freeze
    PASSWORD = "password".freeze
    KEYBOARD_INTERACTIVE = "keyboard-interactive".freeze
    PUBLICKEYPASSWORD = "publickey+password".freeze
    PUBLICKEYKEYBOARD_INTERACTIVE = "publickey+keyboard-interactive".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = LoginMethods.constants.select { |c| LoginMethods::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #LoginMethods" if constantValues.empty?
      value
    end
  end
end
