=begin
#SFTPGo

#SFTPGo REST API

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module SftpgoGeneratedClient
  # S3 Compatible Object Storage configuration details
  class S3Config
    attr_accessor :bucket

    attr_accessor :region

    attr_accessor :access_key

    # the access secret is stored encrypted (AES-256-GCM)
    attr_accessor :access_secret

    # optional endpoint
    attr_accessor :endpoint

    attr_accessor :storage_class

    # the buffer size (in MB) to use for multipart uploads. The minimum allowed part size is 5MB, and if this value is set to zero, the default value (5MB) for the AWS SDK will be used. The minimum allowed value is 5.
    attr_accessor :upload_part_size

    # the number of parts to upload in parallel. If this value is set to zero, the default value (2) will be used
    attr_accessor :upload_concurrency

    # key_prefix is similar to a chroot directory for a local filesystem. If specified the user will only see contents that starts with this prefix and so you can restrict access to a specific virtual folder. The prefix, if not empty, must not start with \"/\" and must end with \"/\". If empty the whole bucket contents will be available
    attr_accessor :key_prefix

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'bucket' => :'bucket',
        :'region' => :'region',
        :'access_key' => :'access_key',
        :'access_secret' => :'access_secret',
        :'endpoint' => :'endpoint',
        :'storage_class' => :'storage_class',
        :'upload_part_size' => :'upload_part_size',
        :'upload_concurrency' => :'upload_concurrency',
        :'key_prefix' => :'key_prefix'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'bucket' => :'String',
        :'region' => :'String',
        :'access_key' => :'String',
        :'access_secret' => :'String',
        :'endpoint' => :'String',
        :'storage_class' => :'String',
        :'upload_part_size' => :'Integer',
        :'upload_concurrency' => :'Integer',
        :'key_prefix' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SftpgoGeneratedClient::S3Config` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SftpgoGeneratedClient::S3Config`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'bucket')
        self.bucket = attributes[:'bucket']
      end

      if attributes.key?(:'region')
        self.region = attributes[:'region']
      end

      if attributes.key?(:'access_key')
        self.access_key = attributes[:'access_key']
      end

      if attributes.key?(:'access_secret')
        self.access_secret = attributes[:'access_secret']
      end

      if attributes.key?(:'endpoint')
        self.endpoint = attributes[:'endpoint']
      end

      if attributes.key?(:'storage_class')
        self.storage_class = attributes[:'storage_class']
      end

      if attributes.key?(:'upload_part_size')
        self.upload_part_size = attributes[:'upload_part_size']
      end

      if attributes.key?(:'upload_concurrency')
        self.upload_concurrency = attributes[:'upload_concurrency']
      end

      if attributes.key?(:'key_prefix')
        self.key_prefix = attributes[:'key_prefix']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @bucket.nil?
        invalid_properties.push('invalid value for "bucket", bucket cannot be nil.')
      end

      if @bucket.to_s.length < 1
        invalid_properties.push('invalid value for "bucket", the character length must be great than or equal to 1.')
      end

      if @region.nil?
        invalid_properties.push('invalid value for "region", region cannot be nil.')
      end

      if @region.to_s.length < 1
        invalid_properties.push('invalid value for "region", the character length must be great than or equal to 1.')
      end

      if !@access_key.nil? && @access_key.to_s.length < 1
        invalid_properties.push('invalid value for "access_key", the character length must be great than or equal to 1.')
      end

      if !@access_secret.nil? && @access_secret.to_s.length < 1
        invalid_properties.push('invalid value for "access_secret", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @bucket.nil?
      return false if @bucket.to_s.length < 1
      return false if @region.nil?
      return false if @region.to_s.length < 1
      return false if !@access_key.nil? && @access_key.to_s.length < 1
      return false if !@access_secret.nil? && @access_secret.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] bucket Value to be assigned
    def bucket=(bucket)
      if bucket.nil?
        fail ArgumentError, 'bucket cannot be nil'
      end

      if bucket.to_s.length < 1
        fail ArgumentError, 'invalid value for "bucket", the character length must be great than or equal to 1.'
      end

      @bucket = bucket
    end

    # Custom attribute writer method with validation
    # @param [Object] region Value to be assigned
    def region=(region)
      if region.nil?
        fail ArgumentError, 'region cannot be nil'
      end

      if region.to_s.length < 1
        fail ArgumentError, 'invalid value for "region", the character length must be great than or equal to 1.'
      end

      @region = region
    end

    # Custom attribute writer method with validation
    # @param [Object] access_key Value to be assigned
    def access_key=(access_key)
      if !access_key.nil? && access_key.to_s.length < 1
        fail ArgumentError, 'invalid value for "access_key", the character length must be great than or equal to 1.'
      end

      @access_key = access_key
    end

    # Custom attribute writer method with validation
    # @param [Object] access_secret Value to be assigned
    def access_secret=(access_secret)
      if !access_secret.nil? && access_secret.to_s.length < 1
        fail ArgumentError, 'invalid value for "access_secret", the character length must be great than or equal to 1.'
      end

      @access_secret = access_secret
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          bucket == o.bucket &&
          region == o.region &&
          access_key == o.access_key &&
          access_secret == o.access_secret &&
          endpoint == o.endpoint &&
          storage_class == o.storage_class &&
          upload_part_size == o.upload_part_size &&
          upload_concurrency == o.upload_concurrency &&
          key_prefix == o.key_prefix
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [bucket, region, access_key, access_secret, endpoint, storage_class, upload_part_size, upload_concurrency, key_prefix].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        SftpgoGeneratedClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
