=begin
#SFTPGo

#SFTPGo REST API

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module SftpgoGeneratedClient
  class User
    attr_accessor :id

    # status:   * `0` user is disabled, login is not allowed   * `1` user is enabled 
    attr_accessor :status

    # username is unique
    attr_accessor :username

    # expiration date as unix timestamp in milliseconds. An expired account cannot login. 0 means no expiration
    attr_accessor :expiration_date

    # password or public key/SSH user certificate are mandatory. If the password has no known hashing algo prefix it will be stored using argon2id. You can send a password hashed as bcrypt or pbkdf2 and it will be stored as is. For security reasons this field is omitted when you search/get users
    attr_accessor :password

    # a password or at least one public key/SSH user certificate are mandatory.
    attr_accessor :public_keys

    # path to the user home directory. The user cannot upload or download files outside this directory. SFTPGo tries to automatically create this folder if missing. Must be an absolute path
    attr_accessor :home_dir

    # mapping between virtual SFTPGo paths and filesystem paths outside the user home directory. Supported for local filesystem only. If one or more of the specified folders are not inside the dataprovider they will be automatically created. You have to create the folder on the filesystem yourself
    attr_accessor :virtual_folders

    # if you run SFTPGo as root user, the created files and directories will be assigned to this uid. 0 means no change, the owner will be the user that runs SFTPGo. Ignored on windows
    attr_accessor :uid

    # if you run SFTPGo as root user, the created files and directories will be assigned to this gid. 0 means no change, the group will be the one of the user that runs SFTPGo. Ignored on windows
    attr_accessor :gid

    # Limit the sessions that a user can open. 0 means unlimited
    attr_accessor :max_sessions

    # Quota as size in bytes. 0 menas unlimited. Please note that quota is updated if files are added/removed via SFTPGo otherwise a quota scan or a manual quota update is needed
    attr_accessor :quota_size

    # Quota as number of files. 0 menas unlimited. Please note that quota is updated if files are added/removed via SFTPGo otherwise a quota scan or a manual quota update is needed
    attr_accessor :quota_files

    attr_accessor :permissions

    attr_accessor :used_quota_size

    attr_accessor :used_quota_files

    # Last quota update as unix timestamp in milliseconds
    attr_accessor :last_quota_update

    # Maximum upload bandwidth as KB/s, 0 means unlimited
    attr_accessor :upload_bandwidth

    # Maximum download bandwidth as KB/s, 0 means unlimited
    attr_accessor :download_bandwidth

    # Last user login as unix timestamp in milliseconds
    attr_accessor :last_login

    attr_accessor :filters

    attr_accessor :filesystem

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'status' => :'status',
        :'username' => :'username',
        :'expiration_date' => :'expiration_date',
        :'password' => :'password',
        :'public_keys' => :'public_keys',
        :'home_dir' => :'home_dir',
        :'virtual_folders' => :'virtual_folders',
        :'uid' => :'uid',
        :'gid' => :'gid',
        :'max_sessions' => :'max_sessions',
        :'quota_size' => :'quota_size',
        :'quota_files' => :'quota_files',
        :'permissions' => :'permissions',
        :'used_quota_size' => :'used_quota_size',
        :'used_quota_files' => :'used_quota_files',
        :'last_quota_update' => :'last_quota_update',
        :'upload_bandwidth' => :'upload_bandwidth',
        :'download_bandwidth' => :'download_bandwidth',
        :'last_login' => :'last_login',
        :'filters' => :'filters',
        :'filesystem' => :'filesystem'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'status' => :'Integer',
        :'username' => :'String',
        :'expiration_date' => :'Integer',
        :'password' => :'String',
        :'public_keys' => :'Array<String>',
        :'home_dir' => :'String',
        :'virtual_folders' => :'Array<VirtualFolder>',
        :'uid' => :'Integer',
        :'gid' => :'Integer',
        :'max_sessions' => :'Integer',
        :'quota_size' => :'Integer',
        :'quota_files' => :'Integer',
        :'permissions' => :'Array<Hash>',
        :'used_quota_size' => :'Integer',
        :'used_quota_files' => :'Integer',
        :'last_quota_update' => :'Integer',
        :'upload_bandwidth' => :'Integer',
        :'download_bandwidth' => :'Integer',
        :'last_login' => :'Integer',
        :'filters' => :'UserFilters',
        :'filesystem' => :'FilesystemConfig'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'password',
        :'public_keys',
        :'virtual_folders',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SftpgoGeneratedClient::User` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SftpgoGeneratedClient::User`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      end

      if attributes.key?(:'expiration_date')
        self.expiration_date = attributes[:'expiration_date']
      end

      if attributes.key?(:'password')
        self.password = attributes[:'password']
      end

      if attributes.key?(:'public_keys')
        if (value = attributes[:'public_keys']).is_a?(Array)
          self.public_keys = value
        end
      end

      if attributes.key?(:'home_dir')
        self.home_dir = attributes[:'home_dir']
      end

      if attributes.key?(:'virtual_folders')
        if (value = attributes[:'virtual_folders']).is_a?(Array)
          self.virtual_folders = value
        end
      end

      if attributes.key?(:'uid')
        self.uid = attributes[:'uid']
      end

      if attributes.key?(:'gid')
        self.gid = attributes[:'gid']
      end

      if attributes.key?(:'max_sessions')
        self.max_sessions = attributes[:'max_sessions']
      end

      if attributes.key?(:'quota_size')
        self.quota_size = attributes[:'quota_size']
      end

      if attributes.key?(:'quota_files')
        self.quota_files = attributes[:'quota_files']
      end

      if attributes.key?(:'permissions')
        if (value = attributes[:'permissions']).is_a?(Array)
          self.permissions = value
        end
      end

      if attributes.key?(:'used_quota_size')
        self.used_quota_size = attributes[:'used_quota_size']
      end

      if attributes.key?(:'used_quota_files')
        self.used_quota_files = attributes[:'used_quota_files']
      end

      if attributes.key?(:'last_quota_update')
        self.last_quota_update = attributes[:'last_quota_update']
      end

      if attributes.key?(:'upload_bandwidth')
        self.upload_bandwidth = attributes[:'upload_bandwidth']
      end

      if attributes.key?(:'download_bandwidth')
        self.download_bandwidth = attributes[:'download_bandwidth']
      end

      if attributes.key?(:'last_login')
        self.last_login = attributes[:'last_login']
      end

      if attributes.key?(:'filters')
        self.filters = attributes[:'filters']
      end

      if attributes.key?(:'filesystem')
        self.filesystem = attributes[:'filesystem']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@id.nil? && @id < 1
        invalid_properties.push('invalid value for "id", must be greater than or equal to 1.')
      end

      if !@uid.nil? && @uid > 65535
        invalid_properties.push('invalid value for "uid", must be smaller than or equal to 65535.')
      end

      if !@uid.nil? && @uid < 0
        invalid_properties.push('invalid value for "uid", must be greater than or equal to 0.')
      end

      if !@gid.nil? && @gid > 65535
        invalid_properties.push('invalid value for "gid", must be smaller than or equal to 65535.')
      end

      if !@gid.nil? && @gid < 0
        invalid_properties.push('invalid value for "gid", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@id.nil? && @id < 1
      status_validator = EnumAttributeValidator.new('Integer', [0, 1])
      return false unless status_validator.valid?(@status)
      return false if !@uid.nil? && @uid > 65535
      return false if !@uid.nil? && @uid < 0
      return false if !@gid.nil? && @gid > 65535
      return false if !@gid.nil? && @gid < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if !id.nil? && id < 1
        fail ArgumentError, 'invalid value for "id", must be greater than or equal to 1.'
      end

      @id = id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('Integer', [0, 1])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] uid Value to be assigned
    def uid=(uid)
      if !uid.nil? && uid > 65535
        fail ArgumentError, 'invalid value for "uid", must be smaller than or equal to 65535.'
      end

      if !uid.nil? && uid < 0
        fail ArgumentError, 'invalid value for "uid", must be greater than or equal to 0.'
      end

      @uid = uid
    end

    # Custom attribute writer method with validation
    # @param [Object] gid Value to be assigned
    def gid=(gid)
      if !gid.nil? && gid > 65535
        fail ArgumentError, 'invalid value for "gid", must be smaller than or equal to 65535.'
      end

      if !gid.nil? && gid < 0
        fail ArgumentError, 'invalid value for "gid", must be greater than or equal to 0.'
      end

      @gid = gid
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          status == o.status &&
          username == o.username &&
          expiration_date == o.expiration_date &&
          password == o.password &&
          public_keys == o.public_keys &&
          home_dir == o.home_dir &&
          virtual_folders == o.virtual_folders &&
          uid == o.uid &&
          gid == o.gid &&
          max_sessions == o.max_sessions &&
          quota_size == o.quota_size &&
          quota_files == o.quota_files &&
          permissions == o.permissions &&
          used_quota_size == o.used_quota_size &&
          used_quota_files == o.used_quota_files &&
          last_quota_update == o.last_quota_update &&
          upload_bandwidth == o.upload_bandwidth &&
          download_bandwidth == o.download_bandwidth &&
          last_login == o.last_login &&
          filters == o.filters &&
          filesystem == o.filesystem
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, status, username, expiration_date, password, public_keys, home_dir, virtual_folders, uid, gid, max_sessions, quota_size, quota_files, permissions, used_quota_size, used_quota_files, last_quota_update, upload_bandwidth, download_bandwidth, last_login, filters, filesystem].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        SftpgoGeneratedClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
