=begin
#SFTPGo

#SFTPGo REST API

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

# Common files
require 'sftpgo_generated_client/api_client'
require 'sftpgo_generated_client/api_error'
require 'sftpgo_generated_client/version'
require 'sftpgo_generated_client/configuration'

# Models
require 'sftpgo_generated_client/models/api_response'
require 'sftpgo_generated_client/models/base_virtual_folder'
require 'sftpgo_generated_client/models/connection_status'
require 'sftpgo_generated_client/models/extensions_filter'
require 'sftpgo_generated_client/models/filesystem_config'
require 'sftpgo_generated_client/models/folder_quota_scan'
require 'sftpgo_generated_client/models/gcs_config'
require 'sftpgo_generated_client/models/login_methods'
require 'sftpgo_generated_client/models/permission'
require 'sftpgo_generated_client/models/quota_scan'
require 'sftpgo_generated_client/models/s3_config'
require 'sftpgo_generated_client/models/supported_protocols'
require 'sftpgo_generated_client/models/transfer'
require 'sftpgo_generated_client/models/user'
require 'sftpgo_generated_client/models/user_filters'
require 'sftpgo_generated_client/models/version_info'
require 'sftpgo_generated_client/models/virtual_folder'
require 'sftpgo_generated_client/models/virtual_folder_all_of'

# APIs
require 'sftpgo_generated_client/api/connections_api'
require 'sftpgo_generated_client/api/folders_api'
require 'sftpgo_generated_client/api/maintenance_api'
require 'sftpgo_generated_client/api/providerstatus_api'
require 'sftpgo_generated_client/api/quota_api'
require 'sftpgo_generated_client/api/users_api'
require 'sftpgo_generated_client/api/version_api'

module SftpgoGeneratedClient
  class << self
    # Customize default settings for the SDK using block.
    #   SftpgoGeneratedClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
