=begin
#SFTPGo

#SFTPGo REST API

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SftpgoGeneratedClient::ProviderstatusApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProviderstatusApi' do
  before do
    # run before each test
    @api_instance = SftpgoGeneratedClient::ProviderstatusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProviderstatusApi' do
    it 'should create an instance of ProviderstatusApi' do
      expect(@api_instance).to be_instance_of(SftpgoGeneratedClient::ProviderstatusApi)
    end
  end

  # unit tests for get_provider_status
  # Get data provider status
  # @param [Hash] opts the optional parameters
  # @return [ApiResponse]
  describe 'get_provider_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
