=begin
#SFTPGo

#SFTPGo REST API

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SftpgoGeneratedClient::UsersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @api_instance = SftpgoGeneratedClient::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@api_instance).to be_instance_of(SftpgoGeneratedClient::UsersApi)
    end
  end

  # unit tests for add_user
  # Adds a new user
  # @param user 
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'add_user test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_user
  # Delete an existing user
  # @param user_id ID of the user to delete
  # @param [Hash] opts the optional parameters
  # @return [ApiResponse]
  describe 'delete_user test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_by_id
  # Find user by ID
  # For security reasons the hashed password is omitted in the response
  # @param user_id ID of the user to retrieve
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'get_user_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_users
  # Returns an array with one or more users
  # For security reasons hashed passwords are omitted in the response
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset 
  # @option opts [Integer] :limit The maximum number of items to return. Max value is 500, default is 100
  # @option opts [String] :order Ordering users by username. Default ASC
  # @option opts [String] :username Filter by username, extact match case sensitive
  # @return [Array<User>]
  describe 'get_users test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_user
  # Update an existing user
  # @param user_id ID of the user to update
  # @param user 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :disconnect Disconnect:   * &#x60;0&#x60; The user will not be disconnected and it will continue to use the old configuration until connected. This is the default   * &#x60;1&#x60; The user will be disconnected after a successful update. It must login again and so it will be forced to use the new configuration 
  # @return [ApiResponse]
  describe 'update_user test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
