require 'spec_helper'
require 'rspec_api_documentation/dsl'
require 'helpers/acceptance_spec_helper'

def standard_analysis_parameters

  parameter :audio_recording_id, 'Requested audio recording id (in path/route)', required: true

  parameter :format, 'Format of the requested file', required: true
  parameter :analysis_id, 'Identifier of the analysis that generated the file'
  parameter :file_name, 'Name of the file to retrieve'

  let(:analysis_id) { 'Test' }
  let(:file_name) { 'test-CASE.csv' }

  let(:raw_post) { params.to_json }
end

resource 'Analysis' do
  header 'Authorization', :authentication_token

  before(:each) do
    # this creates a @write_permission.user with write access to @write_permission.project,
    # a @read_permission.user with read access, as well as
    # a site, audio_recording and audio_event having off the project (see permission_factory.rb)
    @write_permission = FactoryGirl.create(:write_permission) # has to be 'write' so that the uploader has access
    @read_permission = FactoryGirl.create(:read_permission, project: @write_permission.project)
    @admin_user = FactoryGirl.create(:admin)
  end

  after(:each) do
    remove_media_dirs
  end

  # prepare ids needed for paths in requests below
  let(:project_id) { @write_permission.project.id }
  let(:site_id) { @write_permission.project.sites[0].id }
  let(:audio_recording_id) { @write_permission.project.sites[0].audio_recordings[0].id }
  let(:audio_recording) { @write_permission.project.sites[0].audio_recordings[0] }
  let(:audio_event) { @write_permission.project.sites[0].audio_recordings[0].audio_events[0] }

  let(:audio_original) { BawWorkers::Storage::AudioOriginal.new(BawWorkers::Settings.paths.original_audios) }
  let(:audio_cache) { BawWorkers::Storage::AudioCache.new(BawWorkers::Settings.paths.cached_audios) }
  let(:spectrogram_cache) { BawWorkers::Storage::SpectrogramCache.new(BawWorkers::Settings.paths.cached_spectrograms) }
  let(:analysis_cache) { BawWorkers::Storage::AnalysisCache.new(BawWorkers::Settings.paths.cached_analysis_jobs) }

  # prepare authentication_token for different users
  let(:admin_token) { "Token token=\"#{@admin_user.authentication_token}\"" }
  let(:writer_token) { "Token token=\"#{@write_permission.user.authentication_token}\"" }
  let(:reader_token) { "Token token=\"#{@read_permission.user.authentication_token}\"" }
  let(:unconfirmed_token) { "Token token=\"#{FactoryGirl.create(:unconfirmed_user).authentication_token}\"" }
  let(:invalid_token) { "Token token=\"blah blah blah\"" }

  get '/audio_recordings/:audio_recording_id/analysis.:format' do
    standard_analysis_parameters
    let(:authentication_token) { admin_token }
    let(:format) { 'csv' }
    standard_request_options(
        :get,
        'ANALYSIS (as admin, requesting csv)',
        :not_found,
        {
            expected_json_path: 'meta/error/details',
            response_body_content: "file 'test-CASE.csv' generated by analysis 'Test' from audio recording"
        })
  end

  get '/audio_recordings/:audio_recording_id/analysis.:format' do
    standard_analysis_parameters
    let(:authentication_token) { admin_token }
    let(:format) { 'json' }
    standard_request_options(
        :get,
        'ANALYSIS (as admin, requesting json)',
        :unprocessable_entity,
        {
            expected_json_path: 'meta/error/details',
            response_body_content: "Request format 'json' must match requested file extension 'csv'."
        })
  end

  get '/audio_recordings/:audio_recording_id/analysis.:format?file_name=:file_name&analysis_id=:analysis_id' do

    standard_analysis_parameters
    let(:authentication_token) { admin_token }
    let(:format) { 'csv' }
    let(:include_test_file) { true}

    standard_request_options(
        :get,
        'ANALYSIS (as admin)',
        :ok,
        {
            expected_response_content_type: 'text/csv',
            expected_response_has_content: true,
            response_body_content: '{"content":"This is some content."}'
        })
  end

  head '/audio_recordings/:audio_recording_id/analysis.:format?file_name=:file_name&analysis_id=:analysis_id' do

    standard_analysis_parameters
    let(:authentication_token) { admin_token }
    let(:format) { 'csv' }
    let(:include_test_file) { true}

    standard_request_options(
        :head,
        'ANALYSIS (as admin)',
        :ok,
        {
            expected_response_content_type: 'text/csv',
            expected_response_has_content: false
        })
  end
end