=begin
#SFTPGo

#SFTPGo REST API

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SftpgoGeneratedClient::FilesystemConfig
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FilesystemConfig' do
  before do
    # run before each test
    @instance = SftpgoGeneratedClient::FilesystemConfig.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FilesystemConfig' do
    it 'should create an instance of FilesystemConfig' do
      expect(@instance).to be_instance_of(SftpgoGeneratedClient::FilesystemConfig)
    end
  end
  describe 'test attribute "provider"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Integer', [0, 1, 2])
      # validator.allowable_values.each do |value|
      #   expect { @instance.provider = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "s3config"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "gcsconfig"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
