=begin
#SFTPGo

#SFTPGo REST API

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SftpgoGeneratedClient::FolderQuotaScan
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FolderQuotaScan' do
  before do
    # run before each test
    @instance = SftpgoGeneratedClient::FolderQuotaScan.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FolderQuotaScan' do
    it 'should create an instance of FolderQuotaScan' do
      expect(@instance).to be_instance_of(SftpgoGeneratedClient::FolderQuotaScan)
    end
  end
  describe 'test attribute "mapped_path"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "start_time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
