=begin
#SFTPGo

#SFTPGo REST API

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SftpgoGeneratedClient::SupportedProtocols
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SupportedProtocols' do
  before do
    # run before each test
    @instance = SftpgoGeneratedClient::SupportedProtocols.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SupportedProtocols' do
    it 'should create an instance of SupportedProtocols' do
      expect(@instance).to be_instance_of(SftpgoGeneratedClient::SupportedProtocols)
    end
  end
end
