=begin
#SFTPGo

#SFTPGo REST API

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SftpgoGeneratedClient::Transfer
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'Transfer' do
  before do
    # run before each test
    @instance = SftpgoGeneratedClient::Transfer.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Transfer' do
    it 'should create an instance of Transfer' do
      expect(@instance).to be_instance_of(SftpgoGeneratedClient::Transfer)
    end
  end
  describe 'test attribute "operation_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["upload", "download"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.operation_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "path"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "start_time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "size"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
