name: Clean up old CI images

on:
  schedule:
    # Run at midnight on the first day of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - baw-server/workbench-server-ci
          - baw-server/workbench-server-pbs-ci
    steps:
      - name: Delete CI images older than 1 month (${{ matrix.image }})
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: QutEcoacoustics
          account-type: org
          image-names: ${{ matrix.image }}
          cut-off: 1month
          keep-at-least: 1
          token: ${{ secrets.GITHUB_TOKEN }}
